---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hello-world-java
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:master-*
spec:
  releaseName: hello-world-java
  chart:
    git: git@github.com:cakeben/benops
    path: k8s
    ref: master
  values:
    applicationName: hello-world-java
    image:
      repository: 995041947753.dkr.ecr.eu-west-2.amazonaws.com/hello-world-java
      tag: latest
      pullPolicy: IfNotPresent
    containerPorts:
      http:
        port: 3000
        protocol: TCP
    service:
      enabled: true
      ports:
        http:
          port: 3000
          targetPort: http
          protocol: TCP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        external-dns.alpha.kubernetes.io/hostname: helloworld.benops.io
      hosts:
      - helloworld.benops.io
      path: /
      servicePort: http
